version: '3.3'

services:
  restapi:
    build: ./
    container_name: app
    command: ./wait-for-postgres.sh db ./restapi
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
  db:
    restart: always
    container_name: db
    image: postgres:alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
volumes:
  dbdata:
